name: CarbonChatExpansion
version: 1.0.0
main: com.omniblock.carbonchatexpansion.CarbonChatExpansionPlugin
author: Edgron
description: CarbonChat & ChatBubbles integration hook for Omniblock
api-version: 1.20

softdepend:
  - PlaceholderAPI
  - CarbonChat
  - ChatBubbles

commands:
  carbonchatexpansion:
    description: CarbonChatExpansion management commands
    usage: /carbonchatexpansion <reload|debug>
    aliases: [cce]
    permission: carbonchatexpansion.admin

permissions:
  carbonchatexpansion.admin:
    description: Allows access to admin commands
    default: op
