name: CarbonChatExpansion
version: 7.0.0
main: com.omniblock.carbonchatexpansion.CarbonChatExpansionPlugin
author: Omniblock
description: PlaceholderAPI Expansion para CarbonChat - Integración ChatBubbles Modo 5
api-version: 1.20

softdepend:
  - PlaceholderAPI
  - CarbonChat
  - ChatBubbles
