name: CarbonChatExpansion
version: 6.0.0
main: com.omniblock.carbonchatexpansion.CarbonChatExpansionPlugin
author: Omniblock
description: PlaceholderAPI Expansion para CarbonChat
api-version: 1.20

softdepend:
  - PlaceholderAPI
  - CarbonChat
  - ChatBubbles
