name: Build CarbonChatExpansion

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Compilar con Maven
      run: mvn clean package
    
    - name: Subir JAR como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: CarbonChatExpansion
        path: target/CarbonChatExpansion-*.jar
        retention-days: 30
